import express from 'express';
import nocache from 'nocache';
import { attachLocals } from './middleware/locals.js';
import { notFound } from './middleware/notFound.js';
import path from 'path';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname } from 'path';
import connectB from './config/db.js';
import { setupViews } from './config/viewEngine.js';
import globalErrorHandler from './controllers/user/errorController.js';
import userRouter from './routes/user/userRoutes.js';
import adminRouter from './routes/admin/adminRoutes.js';
import passport from './config/passport.js';
import session from './middleware/session.js';
import { logger } from './middleware/logger.js';
import { cartCount, wishlistCount } from './middleware/cartWishlistCounter.js';
const app = express();
dotenv.config();
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
connectB();
app.use('/admin', session.adminSession);
app.use('/', session.userSession);

app.use(passport.initialize());
app.use(passport.session());
app.use(attachLocals);
app.use(nocache());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(logger);
app.use(cartCount);
app.use(wishlistCount);
setupViews(app);
app.use(express.static(path.join(__dirname, 'public')));
app.use('/', userRouter);
app.use('/admin', adminRouter);
app.use(notFound);
app.use(globalErrorHandler);

app.listen(process.env.PORT || 3000, () => {
    console.log(`server running in ${process.env.PORT}`);
});
